In [96]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import f1_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import precision_recall_curve

In [36]:
classif = pd.read_csv('classification.csv')

In [83]:
classif
TP = classif[(classif.true == classif.pred)&(classif.true == 1)].shape[0]
FP = classif[(classif.true == 0)&(classif.pred == 1)].shape[0]
FN = classif[(classif.true == 1)&(classif.pred == 0)].shape[0]
TN = classif[(classif.true == classif.pred)&(classif.true == 0)].shape[0]

In [84]:
print(TP, FP, FN, TN)

43 34 59 64


In [87]:
print( 
    accuracy_score(classif.true,classif.pred),
    precision_score(classif.true,classif.pred),
    recall_score(classif.true,classif.pred),
    f1_score(classif.true,classif.pred)
        )


0.535 0.5584415584415584 0.4215686274509804 0.48044692737430167


In [88]:
score = pd.read_csv('scores.csv ')

In [91]:
score.head()

true  score_logreg  score_svm  score_knn  score_tree
0     0      0.683832   0.145976   0.787063    0.500000
1     1      0.801966   0.239511   1.000000    0.833333
2     0      0.382315  -0.245701   0.000000    0.000000
3     1      0.506797  -0.137058   0.000000    0.105263
4     1      0.488781  -0.154148   0.000000    0.105263

In [95]:
print(
roc_auc_score(score.true,score.score_logreg),
roc_auc_score(score.true,score.score_svm),
roc_auc_score(score.true,score.score_knn),
roc_auc_score(score.true,score.score_tree)
)

0.719187675070028 0.7086834733893557 0.6351540616246498 0.6919267707082833


In [242]:
precision, recall, thresholds = precision_recall_curve(
        score.true, score.score_logreg)
thresholds = np.append(thresholds, [1])
all = precision, recall, thresholds

In [273]:
all_filt = np.where((all[0]>0.1)&(all[1]>=0.7), all,-1)

#print(all[0][129],all[1][129],all[2][129])

In [278]:
all_filt[2][np.where(all[0]==max(all_filt[0]))]


array([0.488522])

In [270]:
all_filt

array([[-1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1.        , -1.        ,
        -1.        , -1.        , -1.        , -1. 

In [201]:
all

array([array([0.49746193, 0.49489796, 0.49230769, 0.49484536, 0.49740933,
       0.49479167, 0.4973822 , 0.49473684, 0.4973545 , 0.5       ,
       0.5026738 , 0.5       , 0.4972973 , 0.5       , 0.50273224,
       0.50549451, 0.50828729, 0.51111111, 0.51396648, 0.51685393,
       0.51977401, 0.52272727, 0.52571429, 0.52873563, 0.53179191,
       0.53488372, 0.5380117 , 0.53529412, 0.53846154, 0.54166667,
       0.54491018, 0.54819277, 0.55151515, 0.54878049, 0.55214724,
       0.54938272, 0.55279503, 0.55625   , 0.55974843, 0.55696203,
       0.56050955, 0.56410256, 0.56129032, 0.56493506, 0.56862745,
       0.56578947, 0.56953642, 0.56666667, 0.5704698 , 0.57432432,
       0.57142857, 0.57534247, 0.57241379, 0.57638889, 0.58041958,
       0.58450704, 0.58156028, 0.58571429, 0.58992806, 0.58695652,
       0.59124088, 0.59558824, 0.6       , 0.59701493, 0.60150376,
       0.60606061, 0.60305344, 0.6       , 0.60465116, 0.609375  ,
       0.61417323, 0.61111111, 0.616     , 0.62096774, 

In [115]:
print(precision.shape, recall.shape, thresholds.shape )

(198,) (198,) (198,)


In [135]:
thresholds = np.append(thresholds, [1])

In [168]:
all2 = np.array([])
all3 = np.append(all2, [[precision,recall]])


In [181]:
all3 = precision,recall,thresholds 

In [272]:
all

(array([0.49746193, 0.49489796, 0.49230769, 0.49484536, 0.49740933,
        0.49479167, 0.4973822 , 0.49473684, 0.4973545 , 0.5       ,
        0.5026738 , 0.5       , 0.4972973 , 0.5       , 0.50273224,
        0.50549451, 0.50828729, 0.51111111, 0.51396648, 0.51685393,
        0.51977401, 0.52272727, 0.52571429, 0.52873563, 0.53179191,
        0.53488372, 0.5380117 , 0.53529412, 0.53846154, 0.54166667,
        0.54491018, 0.54819277, 0.55151515, 0.54878049, 0.55214724,
        0.54938272, 0.55279503, 0.55625   , 0.55974843, 0.55696203,
        0.56050955, 0.56410256, 0.56129032, 0.56493506, 0.56862745,
        0.56578947, 0.56953642, 0.56666667, 0.5704698 , 0.57432432,
        0.57142857, 0.57534247, 0.57241379, 0.57638889, 0.58041958,
        0.58450704, 0.58156028, 0.58571429, 0.58992806, 0.58695652,
        0.59124088, 0.59558824, 0.6       , 0.59701493, 0.60150376,
        0.60606061, 0.60305344, 0.6       , 0.60465116, 0.609375  ,
        0.61417323, 0.61111111, 0.616     , 0.62

In [153]:
all3

array([0.49746193, 0.49489796, 0.49230769, 0.49484536, 0.49740933,
       0.49479167, 0.4973822 , 0.49473684, 0.4973545 , 0.5       ,
       0.5026738 , 0.5       , 0.4972973 , 0.5       , 0.50273224,
       0.50549451, 0.50828729, 0.51111111, 0.51396648, 0.51685393,
       0.51977401, 0.52272727, 0.52571429, 0.52873563, 0.53179191,
       0.53488372, 0.5380117 , 0.53529412, 0.53846154, 0.54166667,
       0.54491018, 0.54819277, 0.55151515, 0.54878049, 0.55214724,
       0.54938272, 0.55279503, 0.55625   , 0.55974843, 0.55696203,
       0.56050955, 0.56410256, 0.56129032, 0.56493506, 0.56862745,
       0.56578947, 0.56953642, 0.56666667, 0.5704698 , 0.57432432,
       0.57142857, 0.57534247, 0.57241379, 0.57638889, 0.58041958,
       0.58450704, 0.58156028, 0.58571429, 0.58992806, 0.58695652,
       0.59124088, 0.59558824, 0.6       , 0.59701493, 0.60150376,
       0.60606061, 0.60305344, 0.6       , 0.60465116, 0.609375  ,
       0.61417323, 0.61111111, 0.616     , 0.62096774, 0.62601

In [156]:
np.append(all2, [[precision],[recall], [thresholds]])

array([0.49746193, 0.49489796, 0.49230769, 0.49484536, 0.49740933,
       0.49479167, 0.4973822 , 0.49473684, 0.4973545 , 0.5       ,
       0.5026738 , 0.5       , 0.4972973 , 0.5       , 0.50273224,
       0.50549451, 0.50828729, 0.51111111, 0.51396648, 0.51685393,
       0.51977401, 0.52272727, 0.52571429, 0.52873563, 0.53179191,
       0.53488372, 0.5380117 , 0.53529412, 0.53846154, 0.54166667,
       0.54491018, 0.54819277, 0.55151515, 0.54878049, 0.55214724,
       0.54938272, 0.55279503, 0.55625   , 0.55974843, 0.55696203,
       0.56050955, 0.56410256, 0.56129032, 0.56493506, 0.56862745,
       0.56578947, 0.56953642, 0.56666667, 0.5704698 , 0.57432432,
       0.57142857, 0.57534247, 0.57241379, 0.57638889, 0.58041958,
       0.58450704, 0.58156028, 0.58571429, 0.58992806, 0.58695652,
       0.59124088, 0.59558824, 0.6       , 0.59701493, 0.60150376,
       0.60606061, 0.60305344, 0.6       , 0.60465116, 0.609375  ,
       0.61417323, 0.61111111, 0.616     , 0.62096774, 0.62601

In [175]:
np.concatenate(([1], [2]))

array([1, 2])

In [178]:
k =[1],[2]

In [179]:
k

([1], [2])

In [212]:
m = np.array([[1,2,3],[23,45,67]])
m[1]

array([23, 45, 67])

In [235]:
l = [1,2,3],[23,45,67]
l[2]

IndexError: tuple index out of range

In [231]:
np.where((m[0]>1)&(m[1]>24),m,None)

array([[None, 2, 3],
       [None, 45, 67]], dtype=object)

In [238]:
all3[0]

array([0.49746193, 0.49489796, 0.49230769, 0.49484536, 0.49740933,
       0.49479167, 0.4973822 , 0.49473684, 0.4973545 , 0.5       ,
       0.5026738 , 0.5       , 0.4972973 , 0.5       , 0.50273224,
       0.50549451, 0.50828729, 0.51111111, 0.51396648, 0.51685393,
       0.51977401, 0.52272727, 0.52571429, 0.52873563, 0.53179191,
       0.53488372, 0.5380117 , 0.53529412, 0.53846154, 0.54166667,
       0.54491018, 0.54819277, 0.55151515, 0.54878049, 0.55214724,
       0.54938272, 0.55279503, 0.55625   , 0.55974843, 0.55696203,
       0.56050955, 0.56410256, 0.56129032, 0.56493506, 0.56862745,
       0.56578947, 0.56953642, 0.56666667, 0.5704698 , 0.57432432,
       0.57142857, 0.57534247, 0.57241379, 0.57638889, 0.58041958,
       0.58450704, 0.58156028, 0.58571429, 0.58992806, 0.58695652,
       0.59124088, 0.59558824, 0.6       , 0.59701493, 0.60150376,
       0.60606061, 0.60305344, 0.6       , 0.60465116, 0.609375  ,
       0.61417323, 0.61111111, 0.616     , 0.62096774, 0.62601

In [219]:
all[3]

IndexError: tuple index out of range